import Hero from "@/components/Hero";
import Header from "@/components/common/Header";
import { Inter } from "next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>Tix By Air</title>
        <meta name="title" content="Tix By Air" />
        <meta
          name="description"
          content="Instantly Track Your Community Engagement!"
        />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://y-kappa-two.vercel.app/" />
        <meta property="og:title" content="Tix By Air" />
        <meta
          property="og:description"
          content="Instantly Track Your Community Engagement!"
        />
        <meta
          property="og:image"
          content="https://y-kappa-two.vercel.app/images/png/nav-logo.png"
        />
        <meta property="twitter:card" content="summary_large_image" />
        <meta
          property="twitter:url"
          content="https://y-kappa-two.vercel.app/"
        />
        <meta property="twitter:title" content="Tix By Air" />
        <meta
          property="twitter:description"
          content="Instantly Track Your Community Engagement!"
        />
        <meta
          property="twitter:image"
          content="https://y-kappa-two.vercel.app/images/png/nav-logo.png"
        ></meta>
      </Head>
      <Header />
      <Hero />
    </>
  );
}
